/************************************************************************
 * Name	 : CreateNewContactController
 * Author : Deloitte Consulting
 * Desc	 : This is the Controller class for the updated logic in Create page for Contacts. Its an extension Controller which checks for duplicates for the new COntact in the system.	
 *
 * Modification Log:
 * ----------------------------------------------------------------------
 * Developer		    		Date			Description
 * ----------------------------------------------------------------------
 * NSebastian@Deloitte		   11/4/2015             Original Version
 * 
 *************************************************************************/
public with sharing class CreateNewContactController {
    
    //Variables

/* Method Name: CreateNewContactController
 * Author Name: NSebastian@Deloitte
 * Description: This is the Constructor
 * Parameters: 
 * Returns:    NA
 */
    public CreateNewContactController() {

    }

/* Method Name: CreateNewContactController
 * Author Name: NSebastian@Deloitte
 * Description: This is the Constructor
 * Parameters: ApexPages.StandardController
 * Returns:    NA
 */
	public CreateNewContactController(ApexPages.StandardController controller) {

    }
	
	//methods

}